### ISSUE TITLE
Boot process takes too long

### ISSUE THREAD

**Issue by halleysouza** [GoogleCloudPlatform/gce-rescue#21]
VM boot, in rescue mode, takes too long and GCE Rescue throws an exception while waiting for startup-script completion.

https://github.com/GoogleCloudPlatform/gce-rescue/blob/bf17bf8465cd191010da56c19e23a00827e3a209/gce_rescue/tasks/metadata.py#L71

Need to find an alternative for this scenario.

https://github.com/GoogleCloudPlatform/gce-rescue/blob/bf17bf8465cd191010da56c19e23a00827e3a209/gce_rescue/tasks/metadata.py#L72

**Comment by tjsmith555** [comment]
Per Halley's request, I am uploading the serial output from the VM after trying to run gce-rescue
[serial-output.txt](https://github.com/GoogleCloudPlatform/gce-rescue/files/12431850/serial-output.txt)

**Comment by halleysouza** [comment]
I can see the agent initiating the startup-script:

```Aug 23 17:08:59 debian google_metadata_script_runner[1511]: Starting startup scripts (version 20230601.00).```

But nothing printing the ending of the scripts. We need try to replicate with the same agents version.

@tjsmith555 I understood that you manually increased the timeout and GCE rescue finally came to an ending, right ? 

If so, what was the value you set ?

@tomerlf1 I believe we still a better option than raising an exception when timing out - Wdyt ?

**Comment by tjsmith555** [comment]
I raised it to 600 seconds in the following code snippet. I assumed this was where I should change the timeout based on the error messages I received, but it may have been a flawed understanding that got me there. 

![image](https://github.com/GoogleCloudPlatform/gce-rescue/assets/100967220/410196aa-190c-4dad-80a1-2ca724feec31)

**Comment by halleysouza** [comment]
@tjsmith555 we are about to release the patch for this issue in our next version. In the meantime you can try the unstable version to check if this fixed your problem. 

```
$ git clone https://github.com/GoogleCloudPlatform/gce-rescue.git -b develop
$ cd gce-rescue/
$ pip install --force-reinstall .
```

Let us know if this is working for you now.
